<UI>:
    MDBoxLayout:
        orientation: 'vertical'
        MDLabel:
            text:"hello kivyMD"
            font_style: 'Subtitle1'
            halign: 'center'
            #color: "green"
            theme_text_color: 'Custom'
            text_color: 0, 0, 1, 1
        MDIcon:
            icon: 'gitlab'
            pos_hint: {"center": .5,"center_y": .5}
            color: "red"